// Copyright (c) 2021 Boston Dynamics, Inc.  All rights reserved.
//
// Downloading, reproducing, distributing or otherwise using the SDK Software
// is subject to the terms and conditions of the Boston Dynamics Software
// Development Kit License (20191101-BDSDK-SL).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: bosdyn/api/data_acquisition_store.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A query parameter which filters the possible set of data identifiters to those
// which contain the same action/group names matching any of the names in the
// set of CaptureActionIds.
type ActionIdQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The action ids to filter with.
	ActionIds []*CaptureActionId `protobuf:"bytes,1,rep,name=action_ids,json=actionIds,proto3" json:"action_ids,omitempty"`
}

func (x *ActionIdQuery) Reset() {
	*x = ActionIdQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionIdQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionIdQuery) ProtoMessage() {}

func (x *ActionIdQuery) ProtoReflect() protoreflect.Message {
	mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionIdQuery.ProtoReflect.Descriptor instead.
func (*ActionIdQuery) Descriptor() ([]byte, []int) {
	return file_bosdyn_api_data_acquisition_store_proto_rawDescGZIP(), []int{0}
}

func (x *ActionIdQuery) GetActionIds() []*CaptureActionId {
	if x != nil {
		return x.ActionIds
	}
	return nil
}

// A query parameter which filters the possible set of data identifiers to
// those with timestamps within the specified range.
type TimeRangeQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Start of the time range to query.
	FromTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from_timestamp,json=fromTimestamp,proto3" json:"from_timestamp,omitempty"`
	// End of the time range to query.
	ToTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to_timestamp,json=toTimestamp,proto3" json:"to_timestamp,omitempty"`
}

func (x *TimeRangeQuery) Reset() {
	*x = TimeRangeQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeRangeQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRangeQuery) ProtoMessage() {}

func (x *TimeRangeQuery) ProtoReflect() protoreflect.Message {
	mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRangeQuery.ProtoReflect.Descriptor instead.
func (*TimeRangeQuery) Descriptor() ([]byte, []int) {
	return file_bosdyn_api_data_acquisition_store_proto_rawDescGZIP(), []int{1}
}

func (x *TimeRangeQuery) GetFromTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.FromTimestamp
	}
	return nil
}

func (x *TimeRangeQuery) GetToTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ToTimestamp
	}
	return nil
}

// The message containing the different query parameters which can be applied to
// the ListData requests.
type DataQueryParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Query:
	//	*DataQueryParams_TimeRange
	//	*DataQueryParams_ActionIds
	Query isDataQueryParams_Query `protobuf_oneof:"query"`
}

func (x *DataQueryParams) Reset() {
	*x = DataQueryParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataQueryParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataQueryParams) ProtoMessage() {}

func (x *DataQueryParams) ProtoReflect() protoreflect.Message {
	mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataQueryParams.ProtoReflect.Descriptor instead.
func (*DataQueryParams) Descriptor() ([]byte, []int) {
	return file_bosdyn_api_data_acquisition_store_proto_rawDescGZIP(), []int{2}
}

func (m *DataQueryParams) GetQuery() isDataQueryParams_Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (x *DataQueryParams) GetTimeRange() *TimeRangeQuery {
	if x, ok := x.GetQuery().(*DataQueryParams_TimeRange); ok {
		return x.TimeRange
	}
	return nil
}

func (x *DataQueryParams) GetActionIds() *ActionIdQuery {
	if x, ok := x.GetQuery().(*DataQueryParams_ActionIds); ok {
		return x.ActionIds
	}
	return nil
}

type isDataQueryParams_Query interface {
	isDataQueryParams_Query()
}

type DataQueryParams_TimeRange struct {
	// Time range to query.
	TimeRange *TimeRangeQuery `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3,oneof"`
}

type DataQueryParams_ActionIds struct {
	// List of action ids to query.
	ActionIds *ActionIdQuery `protobuf:"bytes,2,opt,name=action_ids,json=actionIds,proto3,oneof"`
}

func (*DataQueryParams_TimeRange) isDataQueryParams_Query() {}

func (*DataQueryParams_ActionIds) isDataQueryParams_Query() {}

type StoreImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common request header.
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Image to store.
	Image *ImageCapture `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	// Data identifier of the image.
	DataId *DataIdentifier `protobuf:"bytes,3,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
}

func (x *StoreImageRequest) Reset() {
	*x = StoreImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreImageRequest) ProtoMessage() {}

func (x *StoreImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreImageRequest.ProtoReflect.Descriptor instead.
func (*StoreImageRequest) Descriptor() ([]byte, []int) {
	return file_bosdyn_api_data_acquisition_store_proto_rawDescGZIP(), []int{3}
}

func (x *StoreImageRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *StoreImageRequest) GetImage() *ImageCapture {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *StoreImageRequest) GetDataId() *DataIdentifier {
	if x != nil {
		return x.DataId
	}
	return nil
}

type StoreImageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common response header.
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *StoreImageResponse) Reset() {
	*x = StoreImageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreImageResponse) ProtoMessage() {}

func (x *StoreImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreImageResponse.ProtoReflect.Descriptor instead.
func (*StoreImageResponse) Descriptor() ([]byte, []int) {
	return file_bosdyn_api_data_acquisition_store_proto_rawDescGZIP(), []int{4}
}

func (x *StoreImageResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type StoreMetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common request header.
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Metadata to store.
	Metadata *AssociatedMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Data identifier of the metadata.
	DataId *DataIdentifier `protobuf:"bytes,3,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
}

func (x *StoreMetadataRequest) Reset() {
	*x = StoreMetadataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreMetadataRequest) ProtoMessage() {}

func (x *StoreMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreMetadataRequest.ProtoReflect.Descriptor instead.
func (*StoreMetadataRequest) Descriptor() ([]byte, []int) {
	return file_bosdyn_api_data_acquisition_store_proto_rawDescGZIP(), []int{5}
}

func (x *StoreMetadataRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *StoreMetadataRequest) GetMetadata() *AssociatedMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StoreMetadataRequest) GetDataId() *DataIdentifier {
	if x != nil {
		return x.DataId
	}
	return nil
}

type StoreMetadataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common response header.
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *StoreMetadataResponse) Reset() {
	*x = StoreMetadataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreMetadataResponse) ProtoMessage() {}

func (x *StoreMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreMetadataResponse.ProtoReflect.Descriptor instead.
func (*StoreMetadataResponse) Descriptor() ([]byte, []int) {
	return file_bosdyn_api_data_acquisition_store_proto_rawDescGZIP(), []int{6}
}

func (x *StoreMetadataResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type StoreDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common request header.
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Data to store.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Data identifier of the data.
	DataId *DataIdentifier `protobuf:"bytes,3,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	// File extension to use when writing the data to file.
	FileExtension string `protobuf:"bytes,4,opt,name=file_extension,json=fileExtension,proto3" json:"file_extension,omitempty"`
}

func (x *StoreDataRequest) Reset() {
	*x = StoreDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreDataRequest) ProtoMessage() {}

func (x *StoreDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreDataRequest.ProtoReflect.Descriptor instead.
func (*StoreDataRequest) Descriptor() ([]byte, []int) {
	return file_bosdyn_api_data_acquisition_store_proto_rawDescGZIP(), []int{7}
}

func (x *StoreDataRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *StoreDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StoreDataRequest) GetDataId() *DataIdentifier {
	if x != nil {
		return x.DataId
	}
	return nil
}

func (x *StoreDataRequest) GetFileExtension() string {
	if x != nil {
		return x.FileExtension
	}
	return ""
}

type StoreDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common response header.
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *StoreDataResponse) Reset() {
	*x = StoreDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreDataResponse) ProtoMessage() {}

func (x *StoreDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreDataResponse.ProtoReflect.Descriptor instead.
func (*StoreDataResponse) Descriptor() ([]byte, []int) {
	return file_bosdyn_api_data_acquisition_store_proto_rawDescGZIP(), []int{8}
}

func (x *StoreDataResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type ListCaptureActionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common request header.
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Query parameters for finding action ids.
	Query *DataQueryParams `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *ListCaptureActionsRequest) Reset() {
	*x = ListCaptureActionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCaptureActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCaptureActionsRequest) ProtoMessage() {}

func (x *ListCaptureActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCaptureActionsRequest.ProtoReflect.Descriptor instead.
func (*ListCaptureActionsRequest) Descriptor() ([]byte, []int) {
	return file_bosdyn_api_data_acquisition_store_proto_rawDescGZIP(), []int{9}
}

func (x *ListCaptureActionsRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListCaptureActionsRequest) GetQuery() *DataQueryParams {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListCaptureActionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common response header.
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// List of action ids that satisfied the query parameters.
	ActionIds []*CaptureActionId `protobuf:"bytes,2,rep,name=action_ids,json=actionIds,proto3" json:"action_ids,omitempty"`
}

func (x *ListCaptureActionsResponse) Reset() {
	*x = ListCaptureActionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCaptureActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCaptureActionsResponse) ProtoMessage() {}

func (x *ListCaptureActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCaptureActionsResponse.ProtoReflect.Descriptor instead.
func (*ListCaptureActionsResponse) Descriptor() ([]byte, []int) {
	return file_bosdyn_api_data_acquisition_store_proto_rawDescGZIP(), []int{10}
}

func (x *ListCaptureActionsResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListCaptureActionsResponse) GetActionIds() []*CaptureActionId {
	if x != nil {
		return x.ActionIds
	}
	return nil
}

type ListStoredImagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common request header.
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Query parameters for finding images.
	Query *DataQueryParams `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *ListStoredImagesRequest) Reset() {
	*x = ListStoredImagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStoredImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoredImagesRequest) ProtoMessage() {}

func (x *ListStoredImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoredImagesRequest.ProtoReflect.Descriptor instead.
func (*ListStoredImagesRequest) Descriptor() ([]byte, []int) {
	return file_bosdyn_api_data_acquisition_store_proto_rawDescGZIP(), []int{11}
}

func (x *ListStoredImagesRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListStoredImagesRequest) GetQuery() *DataQueryParams {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListStoredImagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common response header.
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// List of image data identifiers that satisfied the query parameters.
	DataIds []*DataIdentifier `protobuf:"bytes,2,rep,name=data_ids,json=dataIds,proto3" json:"data_ids,omitempty"`
}

func (x *ListStoredImagesResponse) Reset() {
	*x = ListStoredImagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStoredImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoredImagesResponse) ProtoMessage() {}

func (x *ListStoredImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoredImagesResponse.ProtoReflect.Descriptor instead.
func (*ListStoredImagesResponse) Descriptor() ([]byte, []int) {
	return file_bosdyn_api_data_acquisition_store_proto_rawDescGZIP(), []int{12}
}

func (x *ListStoredImagesResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListStoredImagesResponse) GetDataIds() []*DataIdentifier {
	if x != nil {
		return x.DataIds
	}
	return nil
}

type ListStoredMetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common request header.
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Query parameters for finding metadata.
	Query *DataQueryParams `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *ListStoredMetadataRequest) Reset() {
	*x = ListStoredMetadataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStoredMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoredMetadataRequest) ProtoMessage() {}

func (x *ListStoredMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoredMetadataRequest.ProtoReflect.Descriptor instead.
func (*ListStoredMetadataRequest) Descriptor() ([]byte, []int) {
	return file_bosdyn_api_data_acquisition_store_proto_rawDescGZIP(), []int{13}
}

func (x *ListStoredMetadataRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListStoredMetadataRequest) GetQuery() *DataQueryParams {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListStoredMetadataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common response header.
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// List of metadata data identifiers that satisfied the query parameters.
	DataIds []*DataIdentifier `protobuf:"bytes,2,rep,name=data_ids,json=dataIds,proto3" json:"data_ids,omitempty"`
}

func (x *ListStoredMetadataResponse) Reset() {
	*x = ListStoredMetadataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStoredMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoredMetadataResponse) ProtoMessage() {}

func (x *ListStoredMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoredMetadataResponse.ProtoReflect.Descriptor instead.
func (*ListStoredMetadataResponse) Descriptor() ([]byte, []int) {
	return file_bosdyn_api_data_acquisition_store_proto_rawDescGZIP(), []int{14}
}

func (x *ListStoredMetadataResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListStoredMetadataResponse) GetDataIds() []*DataIdentifier {
	if x != nil {
		return x.DataIds
	}
	return nil
}

type ListStoredDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common request header.
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Query parameters for finding data.
	Query *DataQueryParams `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *ListStoredDataRequest) Reset() {
	*x = ListStoredDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStoredDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoredDataRequest) ProtoMessage() {}

func (x *ListStoredDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoredDataRequest.ProtoReflect.Descriptor instead.
func (*ListStoredDataRequest) Descriptor() ([]byte, []int) {
	return file_bosdyn_api_data_acquisition_store_proto_rawDescGZIP(), []int{15}
}

func (x *ListStoredDataRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListStoredDataRequest) GetQuery() *DataQueryParams {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListStoredDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common response header.
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// List of data identifiers that satisfied the query parameters.
	DataIds []*DataIdentifier `protobuf:"bytes,2,rep,name=data_ids,json=dataIds,proto3" json:"data_ids,omitempty"`
}

func (x *ListStoredDataResponse) Reset() {
	*x = ListStoredDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStoredDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoredDataResponse) ProtoMessage() {}

func (x *ListStoredDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bosdyn_api_data_acquisition_store_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoredDataResponse.ProtoReflect.Descriptor instead.
func (*ListStoredDataResponse) Descriptor() ([]byte, []int) {
	return file_bosdyn_api_data_acquisition_store_proto_rawDescGZIP(), []int{16}
}

func (x *ListStoredDataResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListStoredDataResponse) GetDataIds() []*DataIdentifier {
	if x != nil {
		return x.DataIds
	}
	return nil
}

var File_bosdyn_api_data_acquisition_store_proto protoreflect.FileDescriptor

var file_bosdyn_api_data_acquisition_store_proto_rawDesc = []byte{
	0x0a, 0x27, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x61, 0x63, 0x71, 0x75, 0x69, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x62, 0x6f, 0x73, 0x64, 0x79,
	0x6e, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x16, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x61, 0x63, 0x71, 0x75, 0x69, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x0d, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x3a, 0x0a, 0x0a, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x61, 0x70,
	0x74, 0x75, 0x72, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x09, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x22, 0x92, 0x01, 0x0a, 0x0e, 0x54, 0x69, 0x6d, 0x65,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x41, 0x0a, 0x0e, 0x66, 0x72,
	0x6f, 0x6d, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d,
	0x66, 0x72, 0x6f, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x3d, 0x0a,
	0x0c, 0x74, 0x6f, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0b, 0x74, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x93, 0x01, 0x0a,
	0x0f, 0x44, 0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x12, 0x3b, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x48, 0x00, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x3a, 0x0a,
	0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x00, 0x52, 0x09,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x22, 0xab, 0x01, 0x0a, 0x11, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79,
	0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x6f, 0x73,
	0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x43, 0x61, 0x70,
	0x74, 0x75, 0x72, 0x65, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62,
	0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x06, 0x64, 0x61, 0x74, 0x61, 0x49, 0x64,
	0x22, 0x48, 0x0a, 0x12, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0xba, 0x01, 0x0a, 0x14, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79,
	0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x64,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x33, 0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52,
	0x06, 0x64, 0x61, 0x74, 0x61, 0x49, 0x64, 0x22, 0x4b, 0x0a, 0x15, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x32, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x22, 0xb5, 0x01, 0x0a, 0x10, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62, 0x6f, 0x73, 0x64,
	0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x33, 0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x06, 0x64,
	0x61, 0x74, 0x61, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x65, 0x78,
	0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66,
	0x69, 0x6c, 0x65, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x47, 0x0a, 0x11,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x32, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x81, 0x01, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61,
	0x70, 0x74, 0x75, 0x72, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x8c, 0x01, 0x0a, 0x1a, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79,
	0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x0a,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x61,
	0x70, 0x74, 0x75, 0x72, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x09, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x22, 0x7f, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x85, 0x01, 0x0a, 0x18, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62,
	0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x07, 0x64, 0x61, 0x74, 0x61, 0x49, 0x64,
	0x73, 0x22, 0x81, 0x01, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x64,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x31, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x31, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x87, 0x01, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x6f, 0x73,
	0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x07, 0x64, 0x61, 0x74, 0x61, 0x49, 0x64, 0x73, 0x22,
	0x7d, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79,
	0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x62, 0x6f, 0x73,
	0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x83,
	0x01, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x6f, 0x73, 0x64,
	0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x35, 0x0a,
	0x08, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x07, 0x64, 0x61, 0x74,
	0x61, 0x49, 0x64, 0x73, 0x42, 0x4e, 0x42, 0x19, 0x44, 0x61, 0x74, 0x61, 0x41, 0x63, 0x71, 0x75,
	0x69, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x68,
	0x73, 0x73, 0x6e, 0x76, 0x2f, 0x73, 0x70, 0x6f, 0x74, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x72,
	0x65, 0x62, 0x75, 0x69, 0x6c, 0x74, 0x2f, 0x67, 0x6f, 0x2f, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e,
	0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bosdyn_api_data_acquisition_store_proto_rawDescOnce sync.Once
	file_bosdyn_api_data_acquisition_store_proto_rawDescData = file_bosdyn_api_data_acquisition_store_proto_rawDesc
)

func file_bosdyn_api_data_acquisition_store_proto_rawDescGZIP() []byte {
	file_bosdyn_api_data_acquisition_store_proto_rawDescOnce.Do(func() {
		file_bosdyn_api_data_acquisition_store_proto_rawDescData = protoimpl.X.CompressGZIP(file_bosdyn_api_data_acquisition_store_proto_rawDescData)
	})
	return file_bosdyn_api_data_acquisition_store_proto_rawDescData
}

var file_bosdyn_api_data_acquisition_store_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_bosdyn_api_data_acquisition_store_proto_goTypes = []interface{}{
	(*ActionIdQuery)(nil),              // 0: bosdyn.api.ActionIdQuery
	(*TimeRangeQuery)(nil),             // 1: bosdyn.api.TimeRangeQuery
	(*DataQueryParams)(nil),            // 2: bosdyn.api.DataQueryParams
	(*StoreImageRequest)(nil),          // 3: bosdyn.api.StoreImageRequest
	(*StoreImageResponse)(nil),         // 4: bosdyn.api.StoreImageResponse
	(*StoreMetadataRequest)(nil),       // 5: bosdyn.api.StoreMetadataRequest
	(*StoreMetadataResponse)(nil),      // 6: bosdyn.api.StoreMetadataResponse
	(*StoreDataRequest)(nil),           // 7: bosdyn.api.StoreDataRequest
	(*StoreDataResponse)(nil),          // 8: bosdyn.api.StoreDataResponse
	(*ListCaptureActionsRequest)(nil),  // 9: bosdyn.api.ListCaptureActionsRequest
	(*ListCaptureActionsResponse)(nil), // 10: bosdyn.api.ListCaptureActionsResponse
	(*ListStoredImagesRequest)(nil),    // 11: bosdyn.api.ListStoredImagesRequest
	(*ListStoredImagesResponse)(nil),   // 12: bosdyn.api.ListStoredImagesResponse
	(*ListStoredMetadataRequest)(nil),  // 13: bosdyn.api.ListStoredMetadataRequest
	(*ListStoredMetadataResponse)(nil), // 14: bosdyn.api.ListStoredMetadataResponse
	(*ListStoredDataRequest)(nil),      // 15: bosdyn.api.ListStoredDataRequest
	(*ListStoredDataResponse)(nil),     // 16: bosdyn.api.ListStoredDataResponse
	(*CaptureActionId)(nil),            // 17: bosdyn.api.CaptureActionId
	(*timestamppb.Timestamp)(nil),      // 18: google.protobuf.Timestamp
	(*RequestHeader)(nil),              // 19: bosdyn.api.RequestHeader
	(*ImageCapture)(nil),               // 20: bosdyn.api.ImageCapture
	(*DataIdentifier)(nil),             // 21: bosdyn.api.DataIdentifier
	(*ResponseHeader)(nil),             // 22: bosdyn.api.ResponseHeader
	(*AssociatedMetadata)(nil),         // 23: bosdyn.api.AssociatedMetadata
}
var file_bosdyn_api_data_acquisition_store_proto_depIdxs = []int32{
	17, // 0: bosdyn.api.ActionIdQuery.action_ids:type_name -> bosdyn.api.CaptureActionId
	18, // 1: bosdyn.api.TimeRangeQuery.from_timestamp:type_name -> google.protobuf.Timestamp
	18, // 2: bosdyn.api.TimeRangeQuery.to_timestamp:type_name -> google.protobuf.Timestamp
	1,  // 3: bosdyn.api.DataQueryParams.time_range:type_name -> bosdyn.api.TimeRangeQuery
	0,  // 4: bosdyn.api.DataQueryParams.action_ids:type_name -> bosdyn.api.ActionIdQuery
	19, // 5: bosdyn.api.StoreImageRequest.header:type_name -> bosdyn.api.RequestHeader
	20, // 6: bosdyn.api.StoreImageRequest.image:type_name -> bosdyn.api.ImageCapture
	21, // 7: bosdyn.api.StoreImageRequest.data_id:type_name -> bosdyn.api.DataIdentifier
	22, // 8: bosdyn.api.StoreImageResponse.header:type_name -> bosdyn.api.ResponseHeader
	19, // 9: bosdyn.api.StoreMetadataRequest.header:type_name -> bosdyn.api.RequestHeader
	23, // 10: bosdyn.api.StoreMetadataRequest.metadata:type_name -> bosdyn.api.AssociatedMetadata
	21, // 11: bosdyn.api.StoreMetadataRequest.data_id:type_name -> bosdyn.api.DataIdentifier
	22, // 12: bosdyn.api.StoreMetadataResponse.header:type_name -> bosdyn.api.ResponseHeader
	19, // 13: bosdyn.api.StoreDataRequest.header:type_name -> bosdyn.api.RequestHeader
	21, // 14: bosdyn.api.StoreDataRequest.data_id:type_name -> bosdyn.api.DataIdentifier
	22, // 15: bosdyn.api.StoreDataResponse.header:type_name -> bosdyn.api.ResponseHeader
	19, // 16: bosdyn.api.ListCaptureActionsRequest.header:type_name -> bosdyn.api.RequestHeader
	2,  // 17: bosdyn.api.ListCaptureActionsRequest.query:type_name -> bosdyn.api.DataQueryParams
	22, // 18: bosdyn.api.ListCaptureActionsResponse.header:type_name -> bosdyn.api.ResponseHeader
	17, // 19: bosdyn.api.ListCaptureActionsResponse.action_ids:type_name -> bosdyn.api.CaptureActionId
	19, // 20: bosdyn.api.ListStoredImagesRequest.header:type_name -> bosdyn.api.RequestHeader
	2,  // 21: bosdyn.api.ListStoredImagesRequest.query:type_name -> bosdyn.api.DataQueryParams
	22, // 22: bosdyn.api.ListStoredImagesResponse.header:type_name -> bosdyn.api.ResponseHeader
	21, // 23: bosdyn.api.ListStoredImagesResponse.data_ids:type_name -> bosdyn.api.DataIdentifier
	19, // 24: bosdyn.api.ListStoredMetadataRequest.header:type_name -> bosdyn.api.RequestHeader
	2,  // 25: bosdyn.api.ListStoredMetadataRequest.query:type_name -> bosdyn.api.DataQueryParams
	22, // 26: bosdyn.api.ListStoredMetadataResponse.header:type_name -> bosdyn.api.ResponseHeader
	21, // 27: bosdyn.api.ListStoredMetadataResponse.data_ids:type_name -> bosdyn.api.DataIdentifier
	19, // 28: bosdyn.api.ListStoredDataRequest.header:type_name -> bosdyn.api.RequestHeader
	2,  // 29: bosdyn.api.ListStoredDataRequest.query:type_name -> bosdyn.api.DataQueryParams
	22, // 30: bosdyn.api.ListStoredDataResponse.header:type_name -> bosdyn.api.ResponseHeader
	21, // 31: bosdyn.api.ListStoredDataResponse.data_ids:type_name -> bosdyn.api.DataIdentifier
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_bosdyn_api_data_acquisition_store_proto_init() }
func file_bosdyn_api_data_acquisition_store_proto_init() {
	if File_bosdyn_api_data_acquisition_store_proto != nil {
		return
	}
	file_bosdyn_api_header_proto_init()
	file_bosdyn_api_image_proto_init()
	file_bosdyn_api_data_acquisition_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_bosdyn_api_data_acquisition_store_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionIdQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosdyn_api_data_acquisition_store_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeRangeQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosdyn_api_data_acquisition_store_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataQueryParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosdyn_api_data_acquisition_store_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosdyn_api_data_acquisition_store_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreImageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosdyn_api_data_acquisition_store_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreMetadataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosdyn_api_data_acquisition_store_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreMetadataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosdyn_api_data_acquisition_store_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosdyn_api_data_acquisition_store_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosdyn_api_data_acquisition_store_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCaptureActionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosdyn_api_data_acquisition_store_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCaptureActionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosdyn_api_data_acquisition_store_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStoredImagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosdyn_api_data_acquisition_store_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStoredImagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosdyn_api_data_acquisition_store_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStoredMetadataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosdyn_api_data_acquisition_store_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStoredMetadataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosdyn_api_data_acquisition_store_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStoredDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosdyn_api_data_acquisition_store_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStoredDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bosdyn_api_data_acquisition_store_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*DataQueryParams_TimeRange)(nil),
		(*DataQueryParams_ActionIds)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bosdyn_api_data_acquisition_store_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bosdyn_api_data_acquisition_store_proto_goTypes,
		DependencyIndexes: file_bosdyn_api_data_acquisition_store_proto_depIdxs,
		MessageInfos:      file_bosdyn_api_data_acquisition_store_proto_msgTypes,
	}.Build()
	File_bosdyn_api_data_acquisition_store_proto = out.File
	file_bosdyn_api_data_acquisition_store_proto_rawDesc = nil
	file_bosdyn_api_data_acquisition_store_proto_goTypes = nil
	file_bosdyn_api_data_acquisition_store_proto_depIdxs = nil
}
