// Copyright (c) 2022 Boston Dynamics, Inc.  All rights reserved.
//
// Downloading, reproducing, distributing or otherwise using the SDK Software
// is subject to the terms and conditions of the Boston Dynamics Software
// Development Kit License (20191101-BDSDK-SL).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: bosdyn/api/payload_estimation.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadEstimationCommand_Feedback_Status int32

const (
	PayloadEstimationCommand_Feedback_STATUS_UNKNOWN PayloadEstimationCommand_Feedback_Status = 0
	// Completed estimation routine successfully; estimated_payload is populated.
	PayloadEstimationCommand_Feedback_STATUS_COMPLETED PayloadEstimationCommand_Feedback_Status = 1
	// Completed estimation routine successfully, but estimated mass is small enough to
	// not significantly impact mobility; estimated_payload is empty.
	PayloadEstimationCommand_Feedback_STATUS_SMALL_MASS PayloadEstimationCommand_Feedback_Status = 2
	// Estimation routine is currently running; estimated_payload is empty.
	PayloadEstimationCommand_Feedback_STATUS_IN_PROGRESS PayloadEstimationCommand_Feedback_Status = 3
	// Error occurred during the routine; estaimted_payload is empty.
	PayloadEstimationCommand_Feedback_STATUS_ERROR PayloadEstimationCommand_Feedback_Status = 4
)

// Enum value maps for PayloadEstimationCommand_Feedback_Status.
var (
	PayloadEstimationCommand_Feedback_Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_COMPLETED",
		2: "STATUS_SMALL_MASS",
		3: "STATUS_IN_PROGRESS",
		4: "STATUS_ERROR",
	}
	PayloadEstimationCommand_Feedback_Status_value = map[string]int32{
		"STATUS_UNKNOWN":     0,
		"STATUS_COMPLETED":   1,
		"STATUS_SMALL_MASS":  2,
		"STATUS_IN_PROGRESS": 3,
		"STATUS_ERROR":       4,
	}
)

func (x PayloadEstimationCommand_Feedback_Status) Enum() *PayloadEstimationCommand_Feedback_Status {
	p := new(PayloadEstimationCommand_Feedback_Status)
	*p = x
	return p
}

func (x PayloadEstimationCommand_Feedback_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadEstimationCommand_Feedback_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_bosdyn_api_payload_estimation_proto_enumTypes[0].Descriptor()
}

func (PayloadEstimationCommand_Feedback_Status) Type() protoreflect.EnumType {
	return &file_bosdyn_api_payload_estimation_proto_enumTypes[0]
}

func (x PayloadEstimationCommand_Feedback_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadEstimationCommand_Feedback_Status.Descriptor instead.
func (PayloadEstimationCommand_Feedback_Status) EnumDescriptor() ([]byte, []int) {
	return file_bosdyn_api_payload_estimation_proto_rawDescGZIP(), []int{0, 1, 0}
}

type PayloadEstimationCommand_Feedback_Error int32

const (
	PayloadEstimationCommand_Feedback_ERROR_UNKNOWN PayloadEstimationCommand_Feedback_Error = 0
	// No error has occurred.
	PayloadEstimationCommand_Feedback_ERROR_NONE PayloadEstimationCommand_Feedback_Error = 1
	// Robot failed to stand/change stance.
	PayloadEstimationCommand_Feedback_ERROR_FAILED_STAND PayloadEstimationCommand_Feedback_Error = 2
	// Failed to calculate results.
	PayloadEstimationCommand_Feedback_ERROR_NO_RESULTS PayloadEstimationCommand_Feedback_Error = 3
)

// Enum value maps for PayloadEstimationCommand_Feedback_Error.
var (
	PayloadEstimationCommand_Feedback_Error_name = map[int32]string{
		0: "ERROR_UNKNOWN",
		1: "ERROR_NONE",
		2: "ERROR_FAILED_STAND",
		3: "ERROR_NO_RESULTS",
	}
	PayloadEstimationCommand_Feedback_Error_value = map[string]int32{
		"ERROR_UNKNOWN":      0,
		"ERROR_NONE":         1,
		"ERROR_FAILED_STAND": 2,
		"ERROR_NO_RESULTS":   3,
	}
)

func (x PayloadEstimationCommand_Feedback_Error) Enum() *PayloadEstimationCommand_Feedback_Error {
	p := new(PayloadEstimationCommand_Feedback_Error)
	*p = x
	return p
}

func (x PayloadEstimationCommand_Feedback_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadEstimationCommand_Feedback_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_bosdyn_api_payload_estimation_proto_enumTypes[1].Descriptor()
}

func (PayloadEstimationCommand_Feedback_Error) Type() protoreflect.EnumType {
	return &file_bosdyn_api_payload_estimation_proto_enumTypes[1]
}

func (x PayloadEstimationCommand_Feedback_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadEstimationCommand_Feedback_Error.Descriptor instead.
func (PayloadEstimationCommand_Feedback_Error) EnumDescriptor() ([]byte, []int) {
	return file_bosdyn_api_payload_estimation_proto_rawDescGZIP(), []int{0, 1, 1}
}

// Command the robot to stand and execute a routine to estimate the mass properties of an
// unregistered payload attached to the robot.
type PayloadEstimationCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PayloadEstimationCommand) Reset() {
	*x = PayloadEstimationCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosdyn_api_payload_estimation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayloadEstimationCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadEstimationCommand) ProtoMessage() {}

func (x *PayloadEstimationCommand) ProtoReflect() protoreflect.Message {
	mi := &file_bosdyn_api_payload_estimation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadEstimationCommand.ProtoReflect.Descriptor instead.
func (*PayloadEstimationCommand) Descriptor() ([]byte, []int) {
	return file_bosdyn_api_payload_estimation_proto_rawDescGZIP(), []int{0}
}

type PayloadEstimationCommand_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PayloadEstimationCommand_Request) Reset() {
	*x = PayloadEstimationCommand_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosdyn_api_payload_estimation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayloadEstimationCommand_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadEstimationCommand_Request) ProtoMessage() {}

func (x *PayloadEstimationCommand_Request) ProtoReflect() protoreflect.Message {
	mi := &file_bosdyn_api_payload_estimation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadEstimationCommand_Request.ProtoReflect.Descriptor instead.
func (*PayloadEstimationCommand_Request) Descriptor() ([]byte, []int) {
	return file_bosdyn_api_payload_estimation_proto_rawDescGZIP(), []int{0, 0}
}

type PayloadEstimationCommand_Feedback struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Status of the estimation routine.
	Status PayloadEstimationCommand_Feedback_Status `protobuf:"varint,1,opt,name=status,proto3,enum=bosdyn.api.PayloadEstimationCommand_Feedback_Status" json:"status,omitempty"`
	// The approximate progress of the routine, range [0-1].
	Progress float32 `protobuf:"fixed32,2,opt,name=progress,proto3" json:"progress,omitempty"`
	// Error status of the estimation routine.
	Error PayloadEstimationCommand_Feedback_Error `protobuf:"varint,3,opt,name=error,proto3,enum=bosdyn.api.PayloadEstimationCommand_Feedback_Error" json:"error,omitempty"`
	// The resulting payload estimated by the estimation routine.
	EstimatedPayload *Payload `protobuf:"bytes,4,opt,name=estimated_payload,json=estimatedPayload,proto3" json:"estimated_payload,omitempty"`
}

func (x *PayloadEstimationCommand_Feedback) Reset() {
	*x = PayloadEstimationCommand_Feedback{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosdyn_api_payload_estimation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayloadEstimationCommand_Feedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadEstimationCommand_Feedback) ProtoMessage() {}

func (x *PayloadEstimationCommand_Feedback) ProtoReflect() protoreflect.Message {
	mi := &file_bosdyn_api_payload_estimation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadEstimationCommand_Feedback.ProtoReflect.Descriptor instead.
func (*PayloadEstimationCommand_Feedback) Descriptor() ([]byte, []int) {
	return file_bosdyn_api_payload_estimation_proto_rawDescGZIP(), []int{0, 1}
}

func (x *PayloadEstimationCommand_Feedback) GetStatus() PayloadEstimationCommand_Feedback_Status {
	if x != nil {
		return x.Status
	}
	return PayloadEstimationCommand_Feedback_STATUS_UNKNOWN
}

func (x *PayloadEstimationCommand_Feedback) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *PayloadEstimationCommand_Feedback) GetError() PayloadEstimationCommand_Feedback_Error {
	if x != nil {
		return x.Error
	}
	return PayloadEstimationCommand_Feedback_ERROR_UNKNOWN
}

func (x *PayloadEstimationCommand_Feedback) GetEstimatedPayload() *Payload {
	if x != nil {
		return x.EstimatedPayload
	}
	return nil
}

var File_bosdyn_api_payload_estimation_proto protoreflect.FileDescriptor

var file_bosdyn_api_payload_estimation_proto_rawDesc = []byte{
	0x0a, 0x23, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70,
	0x69, 0x1a, 0x18, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf8, 0x03, 0x0a, 0x18,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0xd0, 0x03, 0x0a, 0x08, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b,
	0x12, 0x4c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x34, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x49, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x33, 0x2e, 0x62, 0x6f, 0x73, 0x64,
	0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x73,
	0x74, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e,
	0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x40, 0x0a, 0x11, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x10, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x73, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x4d, 0x41, 0x4c, 0x4c, 0x5f, 0x4d, 0x41, 0x53, 0x53,
	0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x49, 0x4e, 0x5f,
	0x50, 0x52, 0x4f, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x22, 0x58, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x4e, 0x44, 0x10, 0x02,
	0x12, 0x14, 0x0a, 0x10, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x4e, 0x4f, 0x5f, 0x52, 0x45, 0x53,
	0x55, 0x4c, 0x54, 0x53, 0x10, 0x03, 0x42, 0x4b, 0x42, 0x16, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x68, 0x73,
	0x73, 0x6e, 0x76, 0x2f, 0x73, 0x70, 0x6f, 0x74, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x72, 0x65,
	0x62, 0x75, 0x69, 0x6c, 0x74, 0x2f, 0x67, 0x6f, 0x2f, 0x62, 0x6f, 0x73, 0x64, 0x79, 0x6e, 0x2f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bosdyn_api_payload_estimation_proto_rawDescOnce sync.Once
	file_bosdyn_api_payload_estimation_proto_rawDescData = file_bosdyn_api_payload_estimation_proto_rawDesc
)

func file_bosdyn_api_payload_estimation_proto_rawDescGZIP() []byte {
	file_bosdyn_api_payload_estimation_proto_rawDescOnce.Do(func() {
		file_bosdyn_api_payload_estimation_proto_rawDescData = protoimpl.X.CompressGZIP(file_bosdyn_api_payload_estimation_proto_rawDescData)
	})
	return file_bosdyn_api_payload_estimation_proto_rawDescData
}

var file_bosdyn_api_payload_estimation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bosdyn_api_payload_estimation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bosdyn_api_payload_estimation_proto_goTypes = []interface{}{
	(PayloadEstimationCommand_Feedback_Status)(0), // 0: bosdyn.api.PayloadEstimationCommand.Feedback.Status
	(PayloadEstimationCommand_Feedback_Error)(0),  // 1: bosdyn.api.PayloadEstimationCommand.Feedback.Error
	(*PayloadEstimationCommand)(nil),              // 2: bosdyn.api.PayloadEstimationCommand
	(*PayloadEstimationCommand_Request)(nil),      // 3: bosdyn.api.PayloadEstimationCommand.Request
	(*PayloadEstimationCommand_Feedback)(nil),     // 4: bosdyn.api.PayloadEstimationCommand.Feedback
	(*Payload)(nil), // 5: bosdyn.api.Payload
}
var file_bosdyn_api_payload_estimation_proto_depIdxs = []int32{
	0, // 0: bosdyn.api.PayloadEstimationCommand.Feedback.status:type_name -> bosdyn.api.PayloadEstimationCommand.Feedback.Status
	1, // 1: bosdyn.api.PayloadEstimationCommand.Feedback.error:type_name -> bosdyn.api.PayloadEstimationCommand.Feedback.Error
	5, // 2: bosdyn.api.PayloadEstimationCommand.Feedback.estimated_payload:type_name -> bosdyn.api.Payload
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bosdyn_api_payload_estimation_proto_init() }
func file_bosdyn_api_payload_estimation_proto_init() {
	if File_bosdyn_api_payload_estimation_proto != nil {
		return
	}
	file_bosdyn_api_payload_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_bosdyn_api_payload_estimation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayloadEstimationCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosdyn_api_payload_estimation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayloadEstimationCommand_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosdyn_api_payload_estimation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayloadEstimationCommand_Feedback); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bosdyn_api_payload_estimation_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bosdyn_api_payload_estimation_proto_goTypes,
		DependencyIndexes: file_bosdyn_api_payload_estimation_proto_depIdxs,
		EnumInfos:         file_bosdyn_api_payload_estimation_proto_enumTypes,
		MessageInfos:      file_bosdyn_api_payload_estimation_proto_msgTypes,
	}.Build()
	File_bosdyn_api_payload_estimation_proto = out.File
	file_bosdyn_api_payload_estimation_proto_rawDesc = nil
	file_bosdyn_api_payload_estimation_proto_goTypes = nil
	file_bosdyn_api_payload_estimation_proto_depIdxs = nil
}
